# Generated by Django 4.2.6 on 2023-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Опубликовано', 'Опубликовано'), ('Скрыто', 'Скрыто')], default='Опубликовано', max_length=100),
        ),
    ]
