# Generated by Django 4.2.6 on 2023-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(default=None, upload_to='products/', verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(default=None, upload_to='products/', verbose_name='Фото2'),
        ),
    ]
