# Generated by Django 4.2.6 on 2023-11-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_image_three_alter_product_image_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_three',
        ),
    ]
