# Generated by Django 4.2.6 on 2023-11-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_image_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_two',
        ),
    ]
