# Generated by Django 4.2.6 on 2023-10-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('address', models.CharField(default=None, max_length=250)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Неоплачен', 'Неоплачен'), ('Оплачен', 'Оплачен'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен')], default='Неоплачен', max_length=100)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.neworder')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
