# Generated by Django 4.2.6 on 2023-11-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_slug'),
        ('cart', '0002_alter_neworder_options_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='address',
            field=models.CharField(default=None, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='data_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='phone',
            field=models.CharField(default=None, max_length=12, verbose_name='Тел.'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='status',
            field=models.CharField(choices=[('Неоплачен', 'Неоплачен'), ('Оплачен', 'Оплачен'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен')], default='Неоплачен', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
